import { siteProfile } from "@/lib/site-profile";
import type {
  ApprovalRegistryEntry,
  ContentRegistryEntry,
  SourceRegistryEntry,
} from "@/lib/admin-types";

export const contentRegistry: ContentRegistryEntry[] = [
  {
    id: "content-homepage",
    slug: "homepage",
    section: "homepage",
    title: "Ana sayfa",
    body: "Dijital Sosyal Hak Rehberi konumlandırması, test seçimi ve hızlı yönlendirme akışı.",
    seo_title: "D-SHR",
    seo_description:
      "Sosyal hak testlerine ve rehberlere hızlı ulaşmak için sade, güven veren ve açıklayıcı bir başlangıç sayfası.",
    canonical_path: "/",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "content-about",
    slug: "hakkimizda",
    section: "about",
    title: "Hakkımızda sayfası",
    body: `${siteProfile.founderName} için profesyonel geçmiş, uzmanlık ve iletişim kanallarını sade biçimde toplar.`,
    seo_title: "Hakkımızda | D-SHR",
    seo_description:
      "Projenin amacı, güven yaklaşımı, profesyonel geçmiş ve doğrudan iletişim kanalları.",
    canonical_path: "/hakkimizda",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "content-methodology",
    slug: "methodology",
    section: "methodology",
    title: "Yöntem ve sınırlar",
    body: "Ön değerlendirme akışının ne yaptığı, neyi yapmadığı ve güven sınırları.",
    seo_title: "Yöntem ve Sınırlar | D-SHR",
    seo_description:
      "Ön değerlendirme motorunun nasıl çalıştığını ve sonuçların neden resmi karar olmadığını açıklar.",
    canonical_path: "/methodology",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "content-blog",
    slug: "blog",
    section: "blog",
    title: "Blog ve rehberler",
    body: "Test sonrası yönlendirme, kaynaklı içerik ve sosyal hak açıklamaları.",
    seo_title: "Blog ve Rehberler | D-SHR",
    seo_description:
      "Sosyal hak testlerinden sonra okunabilecek rehberler, açıklamalar ve sonraki adım içerikleri.",
    canonical_path: "/blog",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "blog-vatandaslik-maasi",
    slug: "vatandaslik-maasi-2026-kimler-yararlanacak-basvuru-sartlari-ve-tutarlar-belli-oldu",
    section: "blog",
    title: "Vatandaşlık Maaşı 2026: Kimler Yararlanacak, Başvuru Şartları ve Tutarlar Belli Oldu",
    body: "2026 yılında vatandaşlık maaşı (yaşlılık aylığı) kimlere verilecek? Başvuru şartları, gelir kriterleri ve ödeme süreci hakkında kapsamlı rehber.",
    seo_title: "Vatandaşlık Maaşı 2026 | D-SHR",
    seo_description: "2026 vatandaşlık maaşı başvuru şartları, gelir kriterleri ve ödeme süreci.",
    canonical_path: "/blog/vatandaslik-maasi-2026-kimler-yararlanacak-basvuru-sartlari-ve-tutarlar-belli-oldu",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-evde-bakim-maasi",
    slug: "evde-bakim-maasi-2026-gelir-testi-ve-bakim-kademeleri",
    section: "blog",
    title: "Evde Bakım Maaşı 2026: Gelir Testi, Bakım Kademeleri ve Başvuru Rehberi",
    body: "2026 evde bakım maaşı güncel gelir sınırı, ağır-hafif engelli bakım kademeleri ve SYDV başvuru süreci.",
    seo_title: "Evde Bakım Maaşı 2026 | D-SHR",
    seo_description: "2026 evde bakım maaşı gelir sınırı, bakım kademeleri ve başvuru rehberi.",
    canonical_path: "/blog/evde-bakim-maasi-2026-gelir-testi-ve-bakim-kademeleri",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-gss-prim-borcu",
    slug: "gss-prim-borcu-silinmesi-2026-guncel-sartlar-ve-surec",
    section: "blog",
    title: "GSS Prim Borcu Silinmesi 2026: Güncel Şartlar, Süreç ve Başvuru Rehberi",
    body: "2026 GSS prim borcu silinmesi şartları, 5510 sayılı Kanun kapsamında af süreci ve e-Devlet başvuru adımları.",
    seo_title: "GSS Prim Borcu Silinmesi 2026 | D-SHR",
    seo_description: "2026 GSS prim borcu silinmesi şartları ve e-Devlet başvuru süreci.",
    canonical_path: "/blog/gss-prim-borcu-silinmesi-2026-guncel-sartlar-ve-surec",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-engelli-ayligi",
    slug: "engelli-ayligi-2026-ozurlu-raporu-kriterleri-ve-basvuru-rehberi",
    section: "blog",
    title: "Engelli Aylığı 2026: Özürlü Raporu Kriterleri, Başvuru Rehberi ve Güncel Tutarlar",
    body: "2026 engelli aylığı güncel tutarları, Sağlık Bakanlığı Özürlü Sağlık Kurulu raporu kriterleri ve SYDV başvuru süreci.",
    seo_title: "Engelli Aylığı 2026 | D-SHR",
    seo_description: "2026 engelli aylığı rapor kriterleri ve başvuru rehberi.",
    canonical_path: "/blog/engelli-ayligi-2026-ozurlu-raporu-kriterleri-ve-basvuru-rehberi",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-dogum-yardimi",
    slug: "dogum-yardimi-2026-ikiz-ucuz-dogum-odemeleri-ve-basvuru-rehberi",
    section: "blog",
    title: "Doğum Yardımı 2026: İkiz, Üçüz Doğum Ödemeleri ve Başvuru Rehberi",
    body: "2026 doğum yardımı güncel tutarları, ikiz ve üçüz doğum ödemeleri, e-Devlet başvuru adımları ve SED bağlantısı.",
    seo_title: "Doğum Yardımı 2026 | D-SHR",
    seo_description: "2026 doğum yardımı ödemeleri ve başvuru rehberi.",
    canonical_path: "/blog/dogum-yardimi-2026-ikiz-ucuz-dogum-odemeleri-ve-basvuru-rehberi",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-65-yas-evde-bakim",
    slug: "65-yas-ayligi-ve-evde-bakim-birlikteligi-2026-kapsamli-rehber",
    section: "blog",
    title: "65 Yaş Aylığı ve Evde Bakım Maaşı Birlikteliği 2026: Kapsamlı Rehber ve Uygulama İpuçları",
    body: "2026'da 65 yaş aylığı ve evde bakım maaşı birlikte alınabilir mi? Gelir testi, başvuru şartları ve pratik uygulama rehberi.",
    seo_title: "65 Yaş Aylığı ve Evde Bakım Birlikteliği 2026 | D-SHR",
    seo_description: "2026'da 65 yaş aylığı ve evde bakım maaşı birlikte alınabilir mi?",
    canonical_path: "/blog/65-yas-ayligi-ve-evde-bakim-birlikteligi-2026-kapsamli-rehber",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-sed-koruyucu-aile",
    slug: "sed-yardimi-vs-koruyucu-aile-karsilastirmali-analiz-2026",
    section: "blog",
    title: "SED Yardımı vs Koruyucu Aile: Karşılaştırmalı Analiz 2026",
    body: "2026 SED yardımı ve koruyucu aile desteği arasındaki farklar, hak ve sorumluluklar, gelir kriterleri karşılaştırması.",
    seo_title: "SED Yardımı vs Koruyucu Aile 2026 | D-SHR",
    seo_description: "2026 SED yardımı ve koruyucu aile karşılaştırması.",
    canonical_path: "/blog/sed-yardimi-vs-koruyucu-aile-karsilastirmali-analiz-2026",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-engelli-raporu-itiraz",
    slug: "engelli-raporu-itiraz-sureci-hukuki-yol-haritasi-2026",
    section: "blog",
    title: "Engelli Raporu İtiraz Süreci: Hukuki Yol Haritası 2026",
    body: "Engelli Sağlık Kurulu raporuna itiraz süreci, hastane başhekimliği ve İl Sağlık Müdürlüğü başvuru adımları.",
    seo_title: "Engelli Raporu İtiraz 2026 | D-SHR",
    seo_description: "Engelli raporu itiraz süreci ve hukuki yol haritası 2026.",
    canonical_path: "/blog/engelli-raporu-itiraz-sureci-hukuki-yol-haritasi-2026",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "blog-sosyal-hizmetler-kvkk",
    slug: "sosyal-hizmetler-ve-kvkk-kisisel-veri-korumasi-rehberi-2026",
    section: "blog",
    title: "Sosyal Hizmetler ve KVKK: Kişisel Veri Koruması Rehberi 2026",
    body: "Sosyal hizmetlerde KVKK kapsamı, kişisel veri işleme, aydınlatma metni ve haklarınız.",
    seo_title: "Sosyal Hizmetler ve KVKK 2026 | D-SHR",
    seo_description: "Sosyal hizmetlerde KVKK ve kişisel veri koruması rehberi 2026.",
    canonical_path: "/blog/sosyal-hizmetler-ve-kvkk-kisisel-veri-korumasi-rehberi-2026",
    status: "published",
    updated_at: "2026-05-04",
  },
  {
    id: "content-home-care",
    slug: "evde-bakim-maasi",
    section: "tool",
    title: "Evde bakım maaşı",
    body: "Ön değerlendirme, şartlar ve başvuru rehberi için ana sayfa.",
    seo_title: "Evde Bakım Maaşı | D-SHR",
    seo_description:
      "Evde bakım maaşı için ön değerlendirme, rehber ve sonuç açıklamaları tek yerde.",
    canonical_path: "/evde-bakim-maasi",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "content-gss",
    slug: "gss-gelir-testi",
    section: "tool",
    title: "GSS gelir testi",
    body: "Sağlık güvencesi ve gelir testi için hızlı yol.",
    seo_title: "GSS Gelir Testi | D-SHR",
    seo_description:
      "GSS gelir testi için ön değerlendirme ve rehber yönlendirmesi.",
    canonical_path: "/gss-gelir-testi",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "content-old-age",
    slug: "65-yas-ayligi-uygunluk-testi",
    section: "tool",
    title: "65 yaş aylığı",
    body: "Daha büyük yazı ve sade akış ile uygunluk testi.",
    seo_title: "65 Yaş Aylığı Uygunluk Testi | D-SHR",
    seo_description:
      "65 yaş aylığı için uygunluk testi, rehber ve sonraki adım yönlendirmesi.",
    canonical_path: "/65-yas-ayligi-uygunluk-testi",
    status: "published",
    updated_at: "2026-04-02",
  },
  {
    id: "content-birth-grant",
    slug: "dogum-yardimi-uygunluk-testi",
    section: "tool",
    title: "Doğum yardımı",
    body: "Başvuru, ödeme takvimi ve SSS ile tamamlanan akış.",
    seo_title: "Doğum Yardımı Uygunluk Testi | D-SHR",
    seo_description:
      "Doğum yardımı için uygunluk testi, başvuru rehberi ve ödeme takvimi.",
    canonical_path: "/dogum-yardimi-uygunluk-testi",
    status: "published",
    updated_at: "2026-04-02",
  },
];

export const sourceRegistry: SourceRegistryEntry[] = [
  {
    id: "source-site",
    kind: "web",
    title: "Dijital Sosyal Hak Rehberi ana sitesi",
    url: "https://sosyalhakrehberi.com",
    topic_tags: ["homepage", "seo", "guide"],
    trust_level: "internal",
    status: "active",
  },
  {
    id: "source-instagram",
    kind: "web",
    title: "Instagram iletişim kanalı",
    url: "https://www.instagram.com/sosyalhizmet.danismanligi/",
    topic_tags: ["contact", "brand", "community"],
    trust_level: "internal",
    status: "active",
  },
  {
    id: "source-linkedin",
    kind: "web",
    title: "LinkedIn profesyonel profil",
    url: "https://www.linkedin.com/in/senih25/",
    topic_tags: ["about", "trust", "founder"],
    trust_level: "internal",
    status: "active",
  },
  {
    id: "source-cv",
    kind: "pdf",
    title: "Kurucu özgeçmişi",
    file_path: "C:/Users/YeniKullanici/OneDrive/Desktop/KAPSAMLI/SB/Karışık önml/CV SENİH BAYANKULU #1 (1).pdf",
    topic_tags: ["about", "trust", "experience"],
    trust_level: "internal",
    status: "active",
  },
];

export const approvalRegistry: ApprovalRegistryEntry[] = [
  {
    id: "approval-homepage-refresh",
    subject_type: "content",
    subject_id: "content-homepage",
    action: "publish",
    status: "approved",
    created_at: "2026-04-02",
    note: "Ana konumlandırma güncellemesi için hazır.",
  },
  {
    id: "approval-about-refresh",
    subject_type: "content",
    subject_id: "content-about",
    action: "publish",
    status: "pending",
    created_at: "2026-04-02",
    note: "Kişisel ama profesyonel bio güncellemesi bekliyor.",
  },
  {
    id: "approval-analytics",
    subject_type: "analytics",
    subject_id: "provider-integration",
    action: "update",
    status: "pending",
    created_at: "2026-04-02",
    note: "GA4, Search Console ve Clarity anahtarları eklendiğinde aktif hale gelecek.",
  },
];

export function getContentRegistrySummary(): {
  published: number;
  draft: number;
  ready: number;
  archived: number;
} {
  return contentRegistry.reduce(
    (summary, entry) => {
      summary[entry.status] += 1;
      return summary;
    },
    {
      published: 0,
      draft: 0,
      ready: 0,
      archived: 0,
    },
  );
}
